project:
  type: website
  output-dir: docs
  resources:
    - maps/*.html

website:
  title: "winsley_stats19"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: map.qmd
        text: Map
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
    css: styles.css



