project:
  type: website
  output-dir: docs

website:
  title: "winsley_stats19"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: maps/cost_osm_links.html
        text: Cost per road link
      - href: maps/cas_type_sev_map.html
        text: Collision location
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
    css: styles.css



