project:
  type: website
  output-dir: docs

website:
  title: "winsley_stats19"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: docs/cost_osm_links.html
        text: Map2

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



